name: Build Simple Deduplicator

on:
  workflow_dispatch:

jobs:
  mac:
    name: macOS Build
    runs-on: macos-13
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install PyInstaller

      - name: Build macOS app
        run: pyinstaller --noconfirm --clean specs/simple_deduplicator_mac.spec

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mac-dist
          path: dist/**

  windows:
    name: Windows Build
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install PyInstaller winshell

      - name: Build Windows exe
        run: pyinstaller --noconfirm --clean specs/simple_deduplicator_win.spec

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-dist
          path: dist/**

  linux:
    name: Linux Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential libgl1 libegl1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install PyInstaller

      - name: Build Linux bundle
        run: pyinstaller --noconfirm --clean specs/simple_deduplicator_linux.spec

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-dist
          path: dist/**
